

def _file_validation():
    """
    ## Check if the file generated by mapdl
    ## Check if the file has "ET" attributes
    """
    pass

def _regenerate():
    """
    ### If file was not generated by mapdl,
    start a new mapdl session, import file
    and regenerate (such as Hyperworks generated files)

    ### If file was generated by mapdl import file
    and components directly by PyMAPDL-Reader
    """
    pass

def _get_component_names():
    """
    Read the component names manually
    """
    pass

def _read_element_types():
    pass