
from __future__ import annotations
from ansys.mapdl import reader as pymapdl_reader
from pathlib import Path
from structuralanalysistoolbox.mapdl.mesh import Mesh

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import pyvista as pv


def _ansys_mesh(file : str | Path) -> Mesh:
    """
    Creates a PyVista UnstructuredGrid object from
    a .cdb file mesh.
    .cdb file must be generated by mapdl.
    """
    # File Validation
    # Read File with PyMapdl-Reader
    if isinstance(file, str):
        path = Path(file)
    elif isinstance(file, Path):
        path = file
    else: raise TypeError
    if not path.exists(): raise FileNotFoundError
    
    arv = pymapdl_reader.Archive(filename=file) # return type: <class 'ansys.mapdl.reader.archive.Archive'>
                                                # arv.grid type: # <class 'pyvista.core.pointset.UnstructuredGrid'>
    return Mesh(arv)

def _file_validation():
    """
    ## Check if the file generated by mapdl
    ## Check if the file has "ET" attributes
    """
    pass

def _regenerate():
    """
    ### If file was not generated by mapdl,
    start a new mapdl session, import file
    and regenerate (such as Hyperworks generated files)

    ### If file was generated by mapdl import file
    and components directly by PyMAPDL-Reader
    """
    pass

def _export():
    # pymapdl_reader.save_as_archive("pymapl-generated.cdb", arch.grid)
    pass